---
parameters:
  cloudType: ""
  service: ""
  environment: Deploy
  ansiblePlaybook: ""
  gcpKeyData: ""
  apply: false
  deploy: false
  configure: false
  timeout: 90

jobs:
  # - ${{ if eq(parameters.cloudType, 'GCP') }}:
  #     - deployment: GCP
  #       displayName: Deploy GCP infrastructure
  #       environment: ${{ parameters.environment }}
  #       timeoutInMinutes: ${{ parameters.timeout }}
  #       pool:
  #         vmImage: ubuntu-20.04
  #       container: rink72/lab-ado-container-agent:latest
  #       workspace:
  #         clean: all
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - checkout: infrastructure
  #                 displayName: Checkout infrastructure repo
  #               - template: steps/gcp-deploy.yml
  #                 parameters:
  #                   gcpKeyData: ${{ parameters.gcpKeyData }}
  #                   service: ${{ parameters.service }}
  #                   apply: ${{ parameters.apply }}

  - ${{ if eq(parameters.configure, true ) }}:
      - ${{ if ne(parameters.ansiblePlaybook, '') }}:
          - deployment: Ansible
            pool:
              vmImage: ubuntu-latest
            displayName: Configure infrastructure
            environment: ${{ parameters.environment }}
            timeoutInMinutes: ${{ parameters.timeout }}
            workspace:
              clean: all
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: ansible
                      displayName: Checkout ansible repo
                    - ${{ if eq(parameters.cloudType, 'GCP') }}:
                        - template: steps/gcp-ansible.yml
                          parameters:
                            ansiblePlaybook: ${{ parameters.ansiblePlaybook }}
                            gcpKeyData: ${{ parameters.gcpKeyData }}
                            service: ${{ parameters.service }}
                            apply: ${{ parameters.apply }}
