---
parameters:
  cloudType: ""
  service: ""
  environment: Deploy
  terragruntArtifactName: terragrunt
  infrastructureArtifactName: infrastructure
  gcpKeyData: ""
  apply: false
  timeout: 90

jobs:
  - ${{ if eq(parameters.cloudType, 'GCP') }}:
      - deployment: GCP
        displayName: Deploy GCP infrastructure
        environment: ${{ parameters.environment }}
        timeoutInMinutes: ${{ parameters.timeout }}
        pool:
          vmImage: ubuntu-20.04
        container: rink72/lab-ado-container-agent:latest
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: Download artifacts
                - template: steps/gcp-deploy.yml
                  parameters:
                    terragruntArtifactName: ${{ parameters.terragruntArtifactName }}
                    infrastructureArtifactName: ${{ parameters.infrastructureArtifactName }}
                    gcpKeyData: ${{ parameters.gcpKeyData }}
                    service: ${{ parameters.service }}
                    apply: ${{ parameters.apply }}
